In [1]:
import pandas as pd
path_to_data = "..//data//"

df = pd.read_csv(path_to_data+"pm_data.csv")
sensors_df = pd.read_csv(path_to_data+"sensors.csv")

In [4]:
data

      Unnamed: 0   full_date           1          2          5          6
0              0  2017-03-22  148.020337  40.683844  39.022917  33.550382
1              1  2017-03-23   44.308725  29.237465  24.606322  23.765278
2              2  2017-03-24   54.905155  43.675636  32.662021  24.127526
3              3  2017-03-25   67.575610  58.792217  73.688502  57.902710
4              4  2017-03-26   45.677083  48.348401  41.901811  28.811111
...          ...         ...         ...        ...        ...        ...
1291        1291  2020-10-03   59.629346  50.642450  43.423905  28.360000
1292        1292  2020-10-04   69.613621  30.410000  17.520000  21.340000
1293        1293  2020-10-05   79.143255  29.590000  16.530000  20.040000
1294        1294  2020-10-06   48.956855  26.380000  13.220000  17.600000
1295        1295  2020-10-07   36.733843  30.880000  24.571329  27.620000

[1296 rows x 6 columns]

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import acf

data = pd.read_csv("../data/decomp/kusok_1.csv")  # Загрузить файл
season_periods = {}
data.drop(columns=['Unnamed: 0'], inplace=True)
for col in data.columns:
    if col == 'full_date':
        continue
    series = data[col]  # Выбрать временной ряд
    lags = 500  # Достаточно, чтобы захватить возможный сезон
    
    acf_values = acf(series, nlags=lags)
    season_length = acf_values[100:].argmax() + 100
    print(season_length)
    season_periods[col] = season_length

365
356
358
358

In [ ]:
import numpy as np
import pandas as pd

# Определяем среднюю длину сезона
season_length = 360

# Датасет 1: Центрирование на середине данных
centered_data_1 = {}

for col in data.columns:
    if col == 'full_date':
        continue

    series = data[col].dropna()
    N = len(series)

    # Центрируем на середине
    start_idx = max(0, (N - season_length) // 2)
    end_idx = start_idx + season_length

    centered_data_1[col] = series.iloc[start_idx:end_idx].reset_index(drop=True)

df_centered_1 = pd.DataFrame(centered_data_1)
df_centered_1.to_csv("../data/decomp/dataset_centered_middle.csv", index=False)

In [ ]:
# Датасет 2: Индивидуальные сезоны
centered_data_2 = {}

for col in data.columns:
    if col == 'full_date':
        continue

    series = data[col].dropna()
    season_length = season_periods.get(col, 360)  # Если нет в словаре, используем 360

    N = len(series)

    # Центрируем на середине с индивидуальным сезоном
    start_idx = max(0, (N - season_length) // 2)
    end_idx = start_idx + season_length

    centered_data_2[col] = series.iloc[start_idx:end_idx].reset_index(drop=True)

df_centered_2 = pd.DataFrame(centered_data_2)
df_centered_2.to_csv("../data/decomp/dataset_centered_individual.csv", index=False)